services:
  - type: web
    name: url-monitor
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PORT
        value: 8000  # Puerto explícito
